apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-ui
  labels:
    app: chatbot-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-ui
  template:
    metadata:
      labels:
        app: chatbot-ui
    spec:
      containers:
        - name: chatbot-ui
          image: "llm-example/chatbot-ui:latest"
          ports:
            - containerPort: 3000
          env:
            - name: OPENAI_API_HOST
              value: "{api_host}"
            - name: DEFAULT_MODEL
              value: "{default_model}"
            - name: NEXT_PUBLIC_DEFAULT_SYSTEM_PROMPT
              value: "{system_prompt}"
            - name: NEXT_PUBLIC_DEFAULT_TEMPERATURE
              value: "{temperature}"
            - name: LOG_LEVEL
              value: "{log_level}"
---
kind: Service
apiVersion: v1
metadata:
  name: chatbot-ui
  labels:
    app: chatbot-ui
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: chatbot-ui
  type: ClusterIP
